Marian/features/class signup
AcademiaTestarii/laravel-crm pull request #3
Opened 2021-01-07 22:19 UTC by marianDdev

-student login -> redirect catalog -> alege main class -> formular signup -> alege unul dintre cursuri -> dupa submit ->redirect pe student dashboard
-student dashboard afiseaza in prezent doar un welcome Nume Student, "te-ai inscris cu succes la cursul  {{ Nume Curs = ultimul curs la care s-a inscris}}", "Data inceperii cursului: {{ Data start curs }}" si un link inapoi la catalog

2021-01-08 15:12 UTC, ilaura requested changes

2021-01-08 15:12 UTC, ilaura commented on app/Services/RegisterService.php
> +        if ($user->isStudent()) {
mai e o conditie de if($user->isStudent()) la linia 116, unde se face logica pe student si logica de activare a userului pt el. Poti sa muti logica in acelasi if, indiferent ca e la linia 86 sau 116 si sa scoti de tot is_active => 1 de la linia 96 . Asta 1, pt ca se face logica de 2 ori pt useru de aici. Dar eu din ce stiam userul nu se introduce cu is_active =1 din niciunul dintre if-uri, ci primeste un mail de activare al contului (vezi linia 41) iar abia cand da click pe linkul din mail i se activeaza contul.

2021-01-08 15:12 UTC, ilaura commented on resources/views/students/signup.blade.php
> +                                           value="{{ $student->last_name }}" autofocus required>
->getLastName(), getFirstName(), get-uri, toate get-urile :D

2021-01-08 15:12 UTC, ilaura commented on resources/views/students/classes_finished.blade.php
> +                @if (!empty($finished->resources_description)) { ?>
->getLastName(), getFirstName(), get-uri, toate get-urile :D

2021-01-08 15:12 UTC, ilaura commented on resources/views/students/classes_active.blade.php
> +                <h4> {{ $active->title }}</h4>
->getTitle(),  get-uri, toate get-urile :D

2021-01-08 15:58 UTC, marianDdev commented on app/Repositories/ClassesRepository.php
> +                                          ->limit(2)
voiam sa scriu get() si am scris limit() for some reason - n am nicio situatie in care sa am nevoie doar de doua

2021-01-08 16:01 UTC, marianDdev commented on resources/views/students/signup.blade.php
> +                                           value="{{ $student->last_name }}" autofocus required>
au fost situatii cand nu puteam lua valoarea folosind getFieldceva(, dar data viitoare cand se intampla voi gasi o solutie s anu mai ocolesc get-ul

2021-01-08 19:55 UTC, marianDdev commented on app/Http/Controllers/CatalogController.php
> +        foreach ($classes as $class) {
1. <img width="921" alt="Screenshot 2021-01-08 at 21 47 02" src="https://user-images.githubusercontent.com/72664506/104057779-5afb6c80-51fb-11eb-808c-644314cab1f1.png">
variabille definite in blade intre tag-uri de php, in scope-ul unui foreach, nu usnt recunoscute
Solitia ar fi sa nu mai asignam logica unei variabile, asa : Locuri disponibile: {{$class->getStudents() - $class->classStudents()->count()}} 
Ce parere ai?
2. Ai dreptate, wuery-urile din comtroller sunt inutile, le sterg. Ms pt atentionare

2021-01-08 20:02 UTC, marianDdev commented on app/Http/Controllers/CatalogController.php
> +        $student = $this->studentRepository->findByAuthId(Auth::id());
mai sus am definit studentul intr-o alta metoda, nu il pot folosi si aici
<img width="1097" alt="Screenshot 2021-01-08 at 22 01 45" src="https://user-images.githubusercontent.com/72664506/104058954-2dafbe00-51fd-11eb-80cf-61c1469d1263.png">

2021-01-08 20:14 UTC, marianDdev commented on app/Http/Controllers/DashboardController.php
> +        $lastSignedUpClass = Classes::where('registration_start_date', '>=', Carbon::now())->where('id', $lastSigned->class_id)->first();
1. Intra-devar, e inutil query dupa registration_start_date, trebuie scos
2. Multumesc pt sugestie, nu imi venea deloc in minte o denumire relevanta 👍

2021-01-08 20:24 UTC, marianDdev commented on app/Repositories/ClassesRepository.php
> +                                          ->limit(2)
am ster metoda, nu era folosita

2021-01-09 09:29 UTC, ilaura commented on app/Http/Controllers/CatalogController.php
> +        foreach ($classes as $class) {
1. nu sunt recunoscute vizual, de IDE
2. ok

2021-01-09 09:32 UTC, marianDdev commented on app/Http/Controllers/CatalogController.php
> +        foreach ($classes as $class) {
referitor la 1 - in browser, pe url/catalog primeam actuall error de php $class undefined

2021-01-09 09:36 UTC, ilaura commented on resources/views/students/signup.blade.php
> +                                           value="{{ $student->last_name }}" autofocus required>
probabil nu era definit getFiledCeva()

2021-01-09 09:51 UTC, ilaura approved these changes

2021-03-14 11:00 UTC, merged